### ISSUE TITLE
Passing properties (state/actions) to components?

### ISSUE THREAD

**Issue by rantecki** [hyperapp/router#33]
I'm wondering how we pass props to Components used in a Route node.

E.g.

```
<Route path="/" render={Home} />
```

How can we pass the necessary props (state/actions) that Home needs?

I've found myself using a wrapper as a workaround e.g.

```
const view = (state, actions) => {
  const withProps = (Component, props) => ({ match, location }) => (
    <Component match location {...props} />
  );
  return <main>
    <Switch>
      <Route path="/" render={withProps(requireLogin(Home), { state: state.home, actions: actions.home })}/>
    </Switch>
  </main>;
};
```

Is this a good pattern to use, or is there is a better way?

**Comment by JorgeBucaran** [comment]
> Is this a good pattern to use, or is there is a better way?

That's a way to do it. There's no "better" way since this is mostly functional composition and has little to do with how Hyperapp or the Router works.

Depending on what I am doing, I would prefer this:

```jsx
const Home = (state, actions) => props => (...)

const view = (state, actions) => <Route render={Home(state, actions)} />
```

...but in reality, I would try to be more granular and specific of what I pass down to my component. That is, instead of passing the entire state and actions, I would only pass it the bits and pieces it needs/plans to use.
